name: build-packages

on:
  workflow_call:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install build dependencies
        run: pip install --no-cache-dir -U pip . build

      - name: Build package
        run: python -m build --sdist --wheel
      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
