name: cicd
on: 
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  code-scan:
    uses: ./.github/workflows/_code-scan.yml

  build-package:
    needs: code-scan
    if: github.event_name == 'push'
    uses: ./.github/workflows/_build-packages.yml

  release-package:
    needs: build-package
    if: github.event_name == 'push'
    uses: ./.github/workflows/_release-packages.yml
    permissions:
      contents: write
      id-token: write